# Generated by Django 3.2 on 2023-06-02 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_confirmcode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
