# Generated by Django 3.2 on 2023-06-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_confirmcode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_moderator',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
