# Generated by Django 3.2 on 2023-06-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230603_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmcode',
            name='confirmation_code',
            field=models.CharField(max_length=255),
        ),
    ]
