# Generated by Django 3.2 on 2023-06-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_role'),
        ('users', '0013_auto_20230606_1335'),
    ]

    operations = [
    ]
