# Generated by Django 3.2 on 2023-06-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='description',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
