# Generated by Django 3.2 on 2023-06-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_auto_20230606_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre',
            field=models.CharField(default='null_slug', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together={('name', 'genre')},
        ),
    ]
