# Generated by Django 3.2 on 2023-06-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0010_alter_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='genre',
            name='name',
        ),
    ]
