# Generated by Django 3.2 on 2023-06-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0011_auto_20230606_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='name',
        ),
    ]
