# Generated by Django 3.2 on 2023-06-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0021_alter_title_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
